export const theme = {
  colors: {
    bg: "var(--bg)",
    surface: "var(--surface)",
    surfaceHover: "var(--surface-hover)",
    border: "var(--border)",
    textPrimary: "var(--text-primary)",
    textSecondary: "var(--text-secondary)",
    textTertiary: "var(--text-tertiary)",
    accent: "var(--accent)",
    accentHover: "var(--accent-hover)",
    success: "var(--success)",
    warning: "var(--warning)",
    danger: "var(--danger)",
    dangerBg: "var(--danger-bg)",
    dangerBorder: "var(--danger-border)",
    transparent: "transparent",
  },
  typography: {
    fontFamily:
      '"Inter", "Roboto", -apple-system, BlinkMacSystemFont, "Segoe UI", Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif',
    fontMono: '"JetBrains Mono", "Fira Code", "Roboto Mono", monospace',
    sizes: {
      xs: 12,
      sm: 13,
      md: 14,
      lg: 15,
      xl: 16,
      h3: 20,
      h2: 24,
      h1: 28,
    },
    weights: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
  },
  spacing: {
    zero: 0,
    xs: 2,
    sm: 4,
    md: 6,
    lg: 8,
    xl: 12,
    xxl: 16,
    xxxl: 20,
    huge: 24,
    massive: 40,
    giant: 60,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  shadows: {
    none: "none",
    subtle:
      "0 4px 6px -1px rgba(0, 0, 0, 0.5), 0 2px 4px -1px rgba(0, 0, 0, 0.3)",
    glow: "0 0 15px rgba(59, 130, 246, 0.15)",
  },
};
